name: 'App'

on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  app:
    name: 'Octo Domain Watcher'
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Runner
        uses: ./
        id: runner
        with:
          github_labels: watch-domain
          github_token: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Keepalive
        uses: gautamkrishnar/keepalive-workflow@v1
